"""rename field in PartyAchievements table

Revision ID: 016b3953156e
Revises: 73426b514265
Create Date: 2025-05-08 21:17:00.595074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016b3953156e'
down_revision = '73426b514265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_party_achievements_name')
        batch_op.create_index(batch_op.f('ix_party_achievements_text'), ['text'], unique=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_party_achievements_text'))
        batch_op.create_index('ix_party_achievements_name', ['name'], unique=1)
        batch_op.drop_column('text')

    # ### end Alembic commands ###
