"""retired char non-unique name

Revision ID: 31880a98791e
Revises: beb47e39c795
Create Date: 2025-10-15 22:50:30.085543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31880a98791e'
down_revision = 'beb47e39c795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retired_character', schema=None) as batch_op:
        batch_op.drop_index('ix_retired_character_name')
        batch_op.create_index(batch_op.f('ix_retired_character_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retired_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retired_character_name'))
        batch_op.create_index('ix_retired_character_name', ['name'], unique=1)

    # ### end Alembic commands ###
