"""removing timestamp from DB side and setting on the frontend

Revision ID: 56c243bb0e50
Revises: 2b75d39f19a3
Create Date: 2025-10-23 12:52:39.616338

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56c243bb0e50"
down_revision = "2b75d39f19a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.DATETIME(),
            type_=sa.String(length=256),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_notes_timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index("ix_notes_timestamp", ["timestamp"], unique=False)
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.String(length=256),
            type_=sa.DATETIME(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
