"""added party_achievements table

Revision ID: 73426b514265
Revises: 33c8dc9932af
Create Date: 2025-05-06 22:21:57.883449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73426b514265'
down_revision = '33c8dc9932af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('party_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_achievements_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_party_achievements_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_achievements_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_index('ix_party_achievements')
        batch_op.drop_column('achievements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_party_achievements', ['achievements'], unique=1)

    with op.batch_alter_table('party_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_achievements_timestamp'))
        batch_op.drop_index(batch_op.f('ix_party_achievements_party_id'))
        batch_op.drop_index(batch_op.f('ix_party_achievements_name'))

    op.drop_table('party_achievements')
    # ### end Alembic commands ###
