"""reverting timestamp test

Revision ID: b0cb246cb416
Revises: 56c243bb0e50
Create Date: 2025-10-23 12:54:49.926698

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0cb246cb416"
down_revision = "56c243bb0e50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.VARCHAR(length=256),
            type_=sa.DateTime(),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notes_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_timestamp"))
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.DateTime(),
            type_=sa.VARCHAR(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
