"""party and party notes

Revision ID: be555eb87507
Revises: 6c928b5a8cd3
Create Date: 2025-05-06 22:06:49.820050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be555eb87507'
down_revision = '6c928b5a8cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('achievements', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_achievements'), ['achievements'], unique=True)
        batch_op.create_index(batch_op.f('ix_party_location'), ['location'], unique=True)
        batch_op.create_index(batch_op.f('ix_party_name'), ['name'], unique=True)

    op.create_table('party_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('party_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_notes_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_notes_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_notes_timestamp'))
        batch_op.drop_index(batch_op.f('ix_party_notes_party_id'))

    op.drop_table('party_notes')
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_name'))
        batch_op.drop_index(batch_op.f('ix_party_location'))
        batch_op.drop_index(batch_op.f('ix_party_achievements'))

    op.drop_table('party')
    # ### end Alembic commands ###
