"""added reputation to party model

Revision ID: beb47e39c795
Revises: 14cb029ad751
Create Date: 2025-05-08 22:20:54.199087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb47e39c795'
down_revision = '14cb029ad751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reputation', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_party_reputation'), ['reputation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_reputation'))
        batch_op.drop_column('reputation')

    # ### end Alembic commands ###
