"""retired character table

Revision ID: 6c928b5a8cd3
Revises: d3d2a99718ee
Create Date: 2025-05-06 21:41:34.259143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c928b5a8cd3'
down_revision = 'd3d2a99718ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retired_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retired_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retired_character_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retired_character_gold'), ['gold'], unique=False)
        batch_op.create_index(batch_op.f('ix_retired_character_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_retired_character_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retired_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retired_character_name'))
        batch_op.drop_index(batch_op.f('ix_retired_character_level'))
        batch_op.drop_index(batch_op.f('ix_retired_character_gold'))
        batch_op.drop_index(batch_op.f('ix_retired_character_class_id'))

    op.drop_table('retired_character')
    # ### end Alembic commands ###
