"""adjusted field in party achjeivemtns

Revision ID: 14cb029ad751
Revises: 016b3953156e
Create Date: 2025-05-08 21:19:12.313771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14cb029ad751'
down_revision = '016b3953156e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_achievements', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_index('ix_party_achievements_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_achievements', schema=None) as batch_op:
        batch_op.create_index('ix_party_achievements_text', ['text'], unique=1)
        batch_op.alter_column('text',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
