"""retired character table - nullable fields

Revision ID: 33c8dc9932af
Revises: be555eb87507
Create Date: 2025-05-06 22:18:08.247726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c8dc9932af'
down_revision = 'be555eb87507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('achievements',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.alter_column('achievements',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
